name: Curso-Django-CI

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    #configurando  psycopg2-binary #modelo do fórum
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: instalando dependências
        run: |
          pip install -r requirements.txt
          cp contrib/env-sample .env
      - name: flake8
        run: flake8
      - name: test
        run: pytest --cov=pypro
      - name: codecov
        env:
          CODECOV_TOKEN: "40032b70-e939-4580-bf19-89789f45b262"
        run: codecov
